x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
  
  kafka_service:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka_container
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'my_cluster_id'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller 
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_service:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  
  prometheus_server:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
     - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana_dashboard:
    image: grafana/grafana-enterprise
    container_name: grafana_ui_dashboard
    ports:
     - "8989:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus_server
    <<: *default-logging
    restart: always
  
  redis_cache:
    image: redis/redis-stack:latest
    container_name: codemint_redis_cache
    ports:
      - "6379:6379"      # Redis server
      - "8001:8001"      # Redis Insight UI
   
  

volumes:
  data:
  grafana_data:
